
name: Test
on:
  push:
  pull_request:
  schedule:
    - cron: "2 4 * * Fri" # Min Hour day month week (Fridays at 4:02)
jobs:
  test:
    if: github.event_name != 'pull_request' || github.head_ref != 'devel'
    strategy:
      matrix:
        python: [3.8, 3.9]
    name: py${{ matrix.python }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: setup
        run: |
          pip install poetry && poetry install
      - name: test
        run: poetry run poe test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./.coverage
          flags: unittests
          name: async_rundeck
          fail_ci_if_error: true 
          verbose: true